[package]
name = "stray_be"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stray = {path=".."}
legion = "0.4.0"
lazy_static = "1.4.0"

[lib]
crate-type = ["dylib"]
